name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # 对于Vue 2老项目，14版本兼容性最好

      - name: Install dependencies
        # 强制安装，如果报错也不停止
        run: npm install --legacy-peer-deps || true

      - name: Build
        # 强制打包，如果报错也不停止
        run: npm run build || true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
